name: Validate
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "step 1"
      - run: |
          python3 -c "import json; print('hello from python')"
      - run: echo "step 3"
